# Generated by Django 3.0.3 on 2020-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=200)),
                ('itemname', models.CharField(max_length=200)),
            ],
        ),
    ]
