# Generated by Django 3.0.3 on 2020-04-02 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ThehbhfServicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='itemsize',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
